### ISSUE TITLE
Documentation: Windows users can't run from Downloads directory

### ISSUE THREAD

**Issue by brendonthiede** [localstack/cockpit#12] opened 2022-08-23 20:09 UTC
I had used the emailed link to download cockpit as `$env:USERPROFILE\Downloads\LocalStack Cockpit 0.1.1.exe`. Initially I went to the properties and checked the "Unblock" checkbox, clicked "OK" and then double-clicked the file to run it. The app would start but did not show LocalStack as running (I had previously started it from the CLI) and if I tried to "START" from the UI I would immediately get an error message about "spawn C:\... ENOENT". I ended up creating a directory at `$env:LOCALAPPDATA\Programs\LocalStack` and moved the file there as `Cockpit.exe` and then it worked just fine. I recommend adding some documentation for "installing" on Windows.

**Comment by brendonthiede** [comment] 2022-08-23 20:12
I'm actually noticing there is already a folder `$env:APPDATA\localstack-cockpit`, so maybe that's a better location for me to keep the EXE

**Comment by MarcelStranak** [comment] 2023-01-12 09:50
Hi @brendonthiede, 
A new version of LocalStack Cockpit is out, which should resolve your issues under Windows.
You can start the file from any location. I was unable to reproduce the issue you mentioned earlier. 
I will close the issue as resolved, if the issue continues to persist, please reopen the ticket.

**Closed by MarcelStranak** 2023-01-12 09:50 UTC
